"""Initial migration

Revision ID: aaae58ed83fd
Revises: 
Create Date: 2025-12-17 09:45:08.858155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaae58ed83fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source', 'resolved_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source', 'resolved_url',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
