"""Add city_stats table

Revision ID: 8d67cac08016
Revises: 9f7739581e0a
Create Date: 2025-12-20 23:49:47.767073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d67cac08016'
down_revision: Union[str, Sequence[str], None] = '9f7739581e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_stats',
    sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('needs_sharding', sa.Boolean(), nullable=False),
    sa.Column('last_result_count', sa.Integer(), nullable=False),
    sa.Column('hit_limit_count', sa.Integer(), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('city_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_stats_city_name'), ['city_name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_stats_city_name'))

    op.drop_table('city_stats')
    # ### end Alembic commands ###
