"""initial_schema_v4

Revision ID: 9f7739581e0a
Revises: 
Create Date: 2025-12-20 22:23:13.804270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f7739581e0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_google_news',
    sa.Column('google_news_id', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('google_news_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('resolved_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('publisher_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('publisher_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('search_query', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('status', sa.Enum('pending', 'downloaded', 'processed', 'failed', 'ignored', name='sourcestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_google_news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_google_news_google_news_id'), ['google_news_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_source_google_news_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_google_news_status'), ['status'], unique=False)

    op.create_table('unique_event',
    sa.Column('homicide_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('method_of_death', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('date_precision', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('time_of_day', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('neighborhood', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('establishment', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('full_location_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('plus_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('place_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('formatted_address', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('location_precision', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('geocoding_source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('geocoding_confidence', sa.Float(), nullable=True),
    sa.Column('victim_count', sa.Integer(), nullable=True),
    sa.Column('identified_victim_count', sa.Integer(), nullable=True),
    sa.Column('victims_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('perpetrator_count', sa.Integer(), nullable=True),
    sa.Column('identified_perpetrator_count', sa.Integer(), nullable=True),
    sa.Column('security_force_involved', sa.Boolean(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('chronological_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('additional_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merged_data', sa.JSON(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unique_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unique_event_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_unique_event_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_unique_event_homicide_type'), ['homicide_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_unique_event_security_force_involved'), ['security_force_involved'], unique=False)
        batch_op.create_index(batch_op.f('ix_unique_event_state'), ['state'], unique=False)

    op.create_table('raw_event',
    sa.Column('homicide_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('method_of_death', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('date_precision', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('time_of_day', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('neighborhood', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('victim_count', sa.Integer(), nullable=True),
    sa.Column('identified_victim_count', sa.Integer(), nullable=True),
    sa.Column('perpetrator_count', sa.Integer(), nullable=True),
    sa.Column('security_force_involved', sa.Boolean(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('chronological_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extraction_data', sa.JSON(), nullable=True),
    sa.Column('extraction_model', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('extraction_success', sa.Boolean(), nullable=False),
    sa.Column('extraction_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_google_news_id', sa.Integer(), nullable=True),
    sa.Column('unique_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_google_news_id'], ['source_google_news.id'], ),
    sa.ForeignKeyConstraint(['unique_event_id'], ['unique_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_event_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_event_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_event_homicide_type'), ['homicide_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_event_security_force_involved'), ['security_force_involved'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_event_source_google_news_id'), ['source_google_news_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_event_unique_event_id'), ['unique_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_event_unique_event_id'))
        batch_op.drop_index(batch_op.f('ix_raw_event_source_google_news_id'))
        batch_op.drop_index(batch_op.f('ix_raw_event_security_force_involved'))
        batch_op.drop_index(batch_op.f('ix_raw_event_homicide_type'))
        batch_op.drop_index(batch_op.f('ix_raw_event_event_date'))
        batch_op.drop_index(batch_op.f('ix_raw_event_city'))

    op.drop_table('raw_event')
    with op.batch_alter_table('unique_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unique_event_state'))
        batch_op.drop_index(batch_op.f('ix_unique_event_security_force_involved'))
        batch_op.drop_index(batch_op.f('ix_unique_event_homicide_type'))
        batch_op.drop_index(batch_op.f('ix_unique_event_event_date'))
        batch_op.drop_index(batch_op.f('ix_unique_event_city'))

    op.drop_table('unique_event')
    with op.batch_alter_table('source_google_news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_google_news_status'))
        batch_op.drop_index(batch_op.f('ix_source_google_news_published_at'))
        batch_op.drop_index(batch_op.f('ix_source_google_news_google_news_id'))

    op.drop_table('source_google_news')
    # ### end Alembic commands ###
